name: atividade-apache-aula04

services:
  web:
    build:
      context: ./docker/vulnerable-apache
      args:
        HTTPD_VERSION: "2.4.49"
    image: lab-apache-aula04:lab
    ports:
      - "127.0.0.1:8080:80"
    restart: "no"
